sudo: required
services:
  - docker

before_install:
  - docker build -t yasminaguardia2021/docker-react -f Dockerfile.dev . 

  script:
  - docker run -e CI=true yasminaguardia2021/docker-react npm run test